### ISSUE TITLE
Customize the color in Sketch 41.2

### ISSUE THREAD

**Issue by smwalsh1** [mamuso/sketch-designdoc#6]
cannot get the menu and links color to update during export

**Comment by mamuso** [comment]
Hi @smwalsh1, I just pushed a new version of the plugin fixing this issue

**Comment by smwalsh1** [comment]
@mamuso thanks for looking at this, for some reason still not working for me. i downloaded the example file and switched the colors still not exporting correctly. is there some other than just changing the color that i need to do?

**Comment by smwalsh1** [comment]
never mind. all set now. thanks for making the update.
